name: CI (Playwright) Build & Tests

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs: 
  # Build solution
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [ Playwright.SauceDemo ]

    steps:
    - name: Checkout actions
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build project solution
      run: dotnet build ${{ matrix.project }}/${{ matrix.project }}.csproj --configuration Release
    
    - name: Install Playwright browsers
      run: pwsh ${{ matrix.project }}/bin/Release/net8.0/playwright.ps1 install --with-deps

  # Run tests for each project and category
  tests:
    needs: build
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [ Playwright.SauceDemo ]
        category: [ UI, E2E]

    steps:
    - name: Checkout actions
      uses: actions/checkout@v4

    - name: Run ${{ matrix.project }} - ${{ matrix.category }} tests
      run: dotnet test ${{ matrix.project }}/${{ matrix.project }}.csproj --filter Category=${{ matrix.category }} --no-build --configuration Release --logger "trx;LogFileName=${{ matrix.project }}_${{ matrix.category }}_Results.trx"

    - name: Upload ${{ matrix.project }} test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Reports-${{ matrix.project }}-${{ matrix.category }}
        path: ${{ matrix.project }}/Reports/