name: Playwright (.NET) SauceDemo Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs: 
  build-and-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # - name: Restore SauceDemo project
    #   run: dotnet restore Playwright.SauceDemo/Playwright.SauceDemo.csproj

    - name: Build SauceDemo project
      run: dotnet build Playwright.SauceDemo/Playwright.SauceDemo.csproj --configuration Release

    - name: Install playwright browsers
      run: pwsh Playwright.SauceDemo/bin/Debug/net8.0/playwright.ps1 install --with-deps

    - name: Run SauceDemo tests
      run: dotnet test Playwright.SauceDemo/Playwright.SauceDemo.csproj --no-build --configuration Release --logger "trx;LogFileName=SauceDemo_Test_Results.trx"

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: SauceDemo-Report
        path: Playwright.SauceDemo/Reports/

